#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Fullscreen terminal

alacritty --class 'alacritty_fullscreen,alacritty_fullscreen' \
		  -o window.startup_mode="'Fullscreen'" window.padding.x=45 \
		  window.padding.y=45 window.opacity=1.0 font.size=14
