#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>
##
## Fullscreen terminal

alacritty --class 'Fullscreen,Fullscreen' \
		  -o window.startup_mode=fullscreen window.padding.x=45 \
		  window.padding.y=45 window.opacity=1.0 font.size=14
