#!/usr/bin/env bash

## Copyright (C) 2020-2021 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## Openbox Pipemenu to change polybar themes

# Dir
dir="$HOME/.config/polybar"

# Variables and functions
MENUS_LIBDIR='/usr/share/archcraft/openbox/menulib'
if ! . "$MENUS_LIBDIR/archcraft.cfg" 2> /dev/null; then
	echo "Error: Failed to locate archcraft.cfg in $MENUS_LIBDIR" >&2
	exit 1
fi

# Available themes
bitmap=(`ls --hide='launch.sh' $dir/bitmap`)
simple=(`ls --hide='launch.sh' $dir/simple`)

# Main
gen_menu() {
	local csimple=1
	local cbitmap=1
	
	menuStart
	if [[ `ps -ef | grep -i polybar | grep 'bitmap'` || `ps -ef | grep -i polybar | grep 'simple'` ]] ; then
		menuItem "> Default" "bash $HOME/.config/openbox/polybar/launch.sh"
		menuSeparator
	fi
	menuSeparator "Simple"
	for stheme in "${simple[@]}"; do
		menuItem "${csimple}. ${stheme%.*}" "bash $dir/simple/launch.sh --${stheme}"	
		csimple=$(($csimple+1))
	done
	menuSeparator "Bitmap"
	for btheme in "${bitmap[@]}"; do
		menuItem "${cbitmap}. ${btheme%.*}" "bash $dir/bitmap/launch.sh --${btheme}"
		cbitmap=$(($cbitmap+1))
	done
	menuEnd
}

{ gen_menu; exit 0; }
